project: runs/cls_256
name: cls
exist_ok: false
weights: runs/cls_256/cls/weights/best.pt
hyp: data/hyp_cls.yaml
imgsz: 256
epochs: 200
batch_size: 64
workers: 2
device: '2'
port: '12345'
sync_bn: false
adam: false
rect: false
search_cfg: false
resume: false
nosave: false
patience: 60
evolve: null
quad: false
linear_lr: false
local_rank: -1
save_dir: runs/cls_256/cls2
