project: runs/train_debug
name: exp
exist_ok: false
weights: ''
hyp: data/hyp_cls.yaml
imgsz: 640
epochs: 300
batch_size: 8
workers: 0
device: '0'
port: '23456'
sync_bn: false
adam: false
rect: false
search_cfg: false
resume: false
nosave: false
patience: 100
evolve: null
quad: false
linear_lr: false
local_rank: -1
save_dir: runs/train_debug/exp
